### ISSUE TITLE
Pipes.Parse doesn't export a folds function

### ISSUE THREAD

**Issue by commandodev** [Gabriella439/Haskell-Pipes-Foldl-Library#1]
`Pipes.Parse` doesn't seem to have a `folds` function - even at version 3.0 as specified in the `.cabal` file.

``` haskell
-- | Fold each 'Producer' of a 'FreeT'
folds :: (Monad m) => Fold a b -> FreeT (Producer a m) m r -> Producer b m r
folds (L.Fold step begin done) = PP.folds step begin done
```

**Comment by commandodev** [comment]
Actually - It seems that the mentions of FreeT might be a bit out of date too. Is this dead code? Sorry for the noise if so :-)

**Comment by Gabriella439** [comment]
Oops!  Yes, this is dead code.  I should delete this repository.

All this functionality was absorbed by `Pipes.Group`, `Pipes.Extras`, and `Control.Foldl.Text`/`Control.Foldl.ByteString`

**Comment by commandodev** [comment]
OK, thanks for the heads up :-)
